// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouthAndFamilyDB.Server.Data;

namespace YouthAndFamilyDB.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YouthAndFamilyDB.Shared.HouseChurch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HouseChurches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kinzer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ammon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rodriguez"
                        });
                });

            modelBuilder.Entity("YouthAndFamilyDB.Shared.Teen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int");

                    b.Property<int>("HouseChurchId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseChurchId");

                    b.ToTable("Teens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Peter",
                            GradeLevel = 3,
                            HouseChurchId = 2,
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Damion",
                            GradeLevel = 4,
                            HouseChurchId = 1,
                            LastName = "Wayne"
                        });
                });

            modelBuilder.Entity("YouthAndFamilyDB.Shared.Teen", b =>
                {
                    b.HasOne("YouthAndFamilyDB.Shared.HouseChurch", "HouseChurch")
                        .WithMany()
                        .HasForeignKey("HouseChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HouseChurch");
                });
#pragma warning restore 612, 618
        }
    }
}
